debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
constraints = ["tag==pub"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "/{domain}.cert.pem"
    keyFile = "/{domain}.privkey.pem"


[certificatesResolvers.myresolver.acme]
  email = "{email}"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    # used during the challenge
    entryPoint = "http"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
    #entryPoint = "http"


[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{domain}"
watch = true
exposedByDefault = false

[acme]
email = "{email}"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"   
